[local]
search = "population"
target_frame = 903
range = "803:903"
simulate-enemies = false
objective = "earliest-interaction"
target-object = "exit:0"
# secondary_objective = "max-x"
# require-interaction = ["testdoor:0"]
