#!/usr/bin/env python3
"""AI-Generated by ChatGPT 6

Add distance_to_door to every run in tas/level_data.yml (N v1.4).

Place this script beside the 'tas' and 'tas optimiser' directories, then run
from that directory:
    python -m pip install PyYAML
    python add_distance_to_door.py

Optional arguments:
    --yaml PATH          Input YAML (default: tas/level_data.yml).
    --engine-dir PATH    Extracted optimiser (default: tas optimiser).
    --output PATH        Write a separate YAML instead of updating the input.
    --backend python    Force the reference Python engine.
    --backend native    Require the compiled native engine.

The default backend is auto: use the existing native extension when supported,
otherwise use the reference Python engine. This script does not build anything.
For faster execution, build the optimiser's extension first using its supplied
build_native.py, with the same Python interpreter used to run this script.

Each run is a mapping with a 'demo' field containing a combined level/replay.
Exactly the declared input frames are applied, including stored jump-trigger
bits, with enemies enabled. NO extra neutral/completion frame is applied.
Distance is in engine pixels:
    max(0, hypot(player_x - exit_x, player_y - exit_y) - player_r - exit_r)
In v3.38, player_r is 10 and exit_r is 12. Radii/positions are read from the
engine. Overlapping circles have distance 0. The switch position is not used.
For levels with multiple exits, use the nearest exit circle (open or closed).
A missing exit is an error.

Formatting, comments, demos, and other fields are preserved. An existing
'distance_to_door' field is updated. No YAML is written if any run fails.
Writes are atomic; replacing an existing file creates a uniquely named .bak
backup first. All paths are relative to the current working directory.
Requires Python 3.10+ and PyYAML, plus the supplied optimiser source files.
"""
from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime, timezone
import math
import os
from pathlib import Path
import shutil
import sys
import tempfile
import time

FIELD = 'distance_to_door'


def arguments():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--yaml', type=Path, default=Path('tas/level_data.yml'))
    parser.add_argument('--engine-dir', type=Path, default=Path('tas optimiser'))
    parser.add_argument('--output', type=Path)
    parser.add_argument('--backend', choices=('auto', 'native', 'python'), default='auto')
    return parser.parse_args()


def find_runs(yaml, node, path=(), seen=None):
    """Locate demo mappings and reject ambiguous YAML aliases/duplicate keys."""
    if seen is None:
        seen = set()
    if id(node) in seen:
        raise ValueError('YAML aliases are not supported; use separate run mappings')
    seen.add(id(node))
    if isinstance(node, yaml.MappingNode):
        keys = [key.value for key, _ in node.value]
        if any(not isinstance(key, yaml.ScalarNode) or key.tag != 'tag:yaml.org,2002:str'
               for key, _ in node.value):
            raise ValueError(f'{path}: mapping keys must be plain string keys (no merges)')
        if len(set(keys)) != len(keys):
            raise ValueError(f'{path}: duplicate YAML mapping keys')
        if 'demo' in keys:
            if node.flow_style:
                raise ValueError(f'{path}: run must use a block-style YAML mapping')
            yield path, node
        for key, value in node.value:
            yield from find_runs(yaml, value, path + (key.value,), seen)
    elif isinstance(node, yaml.SequenceNode):
        for index, child in enumerate(node.value):
            yield from find_runs(yaml, child, path + (index,), seen)


def simulate_demo(demo, backend, engine, replay, native):
    combined = replay.parse_combined_level_replay(demo)
    if int(combined.replay_string.split(':', 1)[0]) <= 0:
        raise ValueError('replay has no final input frame (declared count must be positive)')
    frames = replay.decode_complex_replay(combined.replay_string).frames
    # Reference parser supplies the actual door geometry even for native runs.
    level = engine.parse_level_string(combined.level_string, simulate_enemies=True)
    doors = [entry for entry in level.static_world.by_ref.values()
             if entry.kind == engine.StaticColliderKind.EXIT_DOOR]
    if not doors:
        raise ValueError('level has no exit circle')
    result = None
    if backend != 'python' and native.NATIVE_CORE_AVAILABLE:
        try:
            result = native.simulate_batch(
                combined.level_string, frames, simulate_enemies=True,
                stop_on_dead=False, stop_on_complete=False)
        except NotImplementedError:
            if backend == 'native':
                raise
    if result is not None:
        if result['consumed'] != len(frames) or result['state']['frame'] != len(frames):
            raise RuntimeError('native engine did not advance through every input frame')
        player = result['state']['player']
        x, y = player['pos']
        radius, dead = player['r'], player['dead']
        complete = result['state']['static_state']['level_complete']
        used = 'native'
    else:
        state = level.initial_state()
        # Do not use simulate()/simulate_through_frame(): they stop on death.
        for frame in frames:
            state.step(frame, level.tiles)
        if state.frame != len(frames):
            raise RuntimeError('Python engine did not advance through every input frame')
        player = state.player
        x, y = player.pos.x, player.pos.y
        radius, dead = player.r, player.dead
        complete = state.static_state.level_complete
        used = 'python'
    gaps = [math.hypot(x - door.x, y - door.y) - radius - door.r for door in doors]
    if not all(math.isfinite(gap) for gap in gaps):
        raise ValueError('non-finite final position/distance')
    return max(0.0, min(gaps)), used, dead, complete, len(frames)


def patch_for_run(yaml, source, node, distance, newline):
    fields = {key.value: (key, value) for key, value in node.value}
    number = repr(distance)  # Full round-trip precision, not display rounding.
    if FIELD in fields:
        _, value = fields[FIELD]
        if not isinstance(value, yaml.ScalarNode) or value.style in ('|', '>'):
            raise ValueError(f'{FIELD} must be a scalar number or null')
        return value.start_mark.index, value.end_mark.index, number
    key, _ = fields['demo']
    start = source.rfind('\n', 0, key.start_mark.index) + 1
    indent = source[start:key.start_mark.index]
    if indent.strip():
        raise ValueError('demo key must start on its own indented line')
    return start, start, f'{indent}{FIELD}: {number}{newline}'


def atomic_save(destination, content):
    destination.parent.mkdir(parents=True, exist_ok=True)
    backup = None
    temp_path = None
    try:
        with tempfile.NamedTemporaryFile(dir=destination.parent,
                                         prefix=destination.name + '.',
                                         suffix='.tmp', delete=False) as handle:
            temp_path = Path(handle.name)
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        if destination.exists():
            stamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ')
            backup = destination.with_name(destination.name + '.' + stamp + '.bak')
            # Exclusive create ensures an earlier backup can never be overwritten.
            with destination.open('rb') as src, backup.open('xb') as dst:
                shutil.copyfileobj(src, dst)
            shutil.copystat(destination, backup)
            shutil.copymode(destination, temp_path)
        os.replace(temp_path, destination)
    finally:
        if temp_path is not None and temp_path.exists():
            temp_path.unlink()
    return backup


def main():
    args = arguments()
    try:
        import yaml
    except ImportError:
        raise RuntimeError('install PyYAML: python -m pip install PyYAML') from None
    engine_dir = args.engine_dir.resolve()
    for filename in ('nv14_engine.py', 'nv14_replay.py', 'nv14_native.py'):
        if not (engine_dir / filename).is_file():
            raise FileNotFoundError(f'missing {engine_dir / filename}; extract the optimiser first')
    sys.path.insert(0, str(engine_dir))
    import nv14_engine as engine
    import nv14_replay as replay
    import nv14_native as native
    if args.backend == 'native':
        native.require_native()
    source_path = args.yaml.resolve()
    destination = (args.output or source_path).resolve()
    original_bytes = source_path.read_bytes()
    source = original_bytes.decode('utf-8')
    newline = '\r\n' if '\r\n' in source else '\n'
    document = yaml.compose(source, Loader=yaml.SafeLoader)
    if document is None:
        raise ValueError('YAML is empty')
    runs = list(find_runs(yaml, document))
    if not runs:
        raise ValueError('no run mappings containing demo fields found')
    expected = yaml.safe_load(source)
    print(f'Processing {len(runs)} runs; enemies enabled; no extra neutral frame.', flush=True)
    if args.backend == 'auto' and not native.NATIVE_CORE_AVAILABLE:
        print('Native extension unavailable; using the slower Python engine.', flush=True)
    edits, failures = [], []
    counts = Counter()
    started = time.monotonic()
    for index, (path, node) in enumerate(runs, 1):
        label = '/'.join(map(str, path))
        try:
            row = expected
            for key in path:
                row = row[key]
            if not isinstance(row['demo'], str):
                raise ValueError('demo must be a string')
            distance, used, dead, complete, ticks = simulate_demo(
                row['demo'], args.backend, engine, replay, native)
            edits.append(patch_for_run(yaml, source, node, distance, newline))
            row[FIELD] = distance
            counts[used] += 1
            counts['ticks'] += ticks
            if dead or complete:
                counts['warnings'] += 1
                print(f'WARNING {label}: dead={dead}, complete={complete} at final input; '
                      'distance still records the engine state at that frame.', file=sys.stderr)
        except Exception as exc:
            failures.append(f'{label}: {type(exc).__name__}: {exc}')
            print('ERROR ' + failures[-1], file=sys.stderr, flush=True)
        if index == 1 or index % 25 == 0 or index == len(runs):
            print(f'{index}/{len(runs)} runs ({time.monotonic() - started:.1f}s)', flush=True)
    if failures:
        raise RuntimeError(f'{len(failures)} run(s) failed; YAML was not written')
    for start, end, replacement in sorted(edits, reverse=True):
        source = source[:start] + replacement + source[end:]
    if yaml.safe_load(source) != expected:
        raise RuntimeError('edited YAML did not pass content validation; nothing written')
    # Avoid silently replacing edits made while the simulations were running.
    if source_path.read_bytes() != original_bytes:
        raise RuntimeError('input YAML changed during simulation; nothing written')
    backup = atomic_save(destination, source.encode('utf-8'))
    print(f'Saved {destination}: {len(runs)} distances, {counts["ticks"]:,} inputs '
          f'({counts["native"]} native / {counts["python"]} Python; '
          f'{counts["warnings"]} terminal-state warnings).')
    if backup:
        print(f'Backup: {backup}')


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('\nInterrupted.', file=sys.stderr)
        sys.exit(130)
    except Exception as exc:
        print(f'ERROR: {exc}', file=sys.stderr)
        sys.exit(1)
