FROM debian:12

# Extended from https://github.com/clementgallet/libTAS/blob/master/Dockerfile

# A version of the Dockerfile to get sound to work in libTAS inside the container
# Actually not very useful since you don't need sound to work in container for sound to work during encoding
# Run with:
# docker run -it -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.Xauthority:/root/.Xauthority:rw --net=host -v /home/$whoami/nv14_TAS/docker_volume:/home/taser/tas/ -v /run/user/$UID/pulse:/run/user/$UID/pulse -e PULSE_SERVER=unix:/run/user/$UID/pulse/native -v /etc/machine-id:/etc/machine-id:ro --group-add audio --cap-add=cap_checkpoint_restore libtas_sound

# update
  RUN dpkg --add-architecture i386
  RUN apt-get update 

# Sound
# This is for sound for the final recording. You won't need sound for
# TASing (it breaks savestates). You can comment this line if
# necessary
  RUN apt-get install -y pulseaudio pulseaudio-utils alsa-utils \
        libasound2-plugins libasound2 libasound2-dev \
        libpulse0 libpulse-dev

# libtas
  # dependencies
    # main
      RUN apt-get -y install build-essential automake pkg-config libx11-dev libx11-xcb-dev qtbase5-dev libsdl2-dev libxcb1-dev libxcb-keysyms1-dev libxcb-xkb-dev libxcb-cursor-dev libxcb-randr0-dev libudev-dev libasound2-dev libavutil-dev libswresample-dev ffmpeg liblua5.4-dev libcap-dev libxcb-xinput-dev

    # HUD
      RUN apt-get -y install libfreetype6-dev libfontconfig1-dev

    # fonts
      RUN apt-get -y install libfreetype6-dev libfontconfig1-dev
      RUN apt-get -y install fonts-liberation

    # i386
      RUN apt-get -y install g++-multilib
      RUN apt-get -y install libx11-6:i386 libx11-dev:i386 libx11-xcb1:i386 libx11-xcb-dev:i386 libasound2:i386 libasound2-dev:i386 libavutil57:i386 libswresample4:i386 libfreetype6:i386 libfreetype6-dev:i386 libfontconfig1:i386 libfontconfig1-dev:i386

  # install libTAS
    RUN apt-get -y install git wget
    RUN mkdir /root/src
    RUN cd /root/src && git clone https://github.com/clementgallet/libTAS.git
    # pin version (this version works)
    RUN cd /root/src/libTAS && ./build.sh --with-i386 --enable-pulseaudio
    RUN cd /root/src/libTAS/build && make install

# ruffle
  RUN apt-get update && apt-get install -y \
        libasound2-dev \
        libudev-dev \
        default-jre-headless \
        g++
  RUN apt-get install -y curl
  RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
  RUN cd /root/src/ && git clone https://github.com/ruffle-rs/ruffle.git
  # pin version
  RUN cd /root/src/ruffle && git checkout fa9c6627bd86511de1b710dcf42708dc55c44e3e
  # RUN apt-get install -y cargo
  ENV PATH="/root/.cargo/bin:${PATH}"
  RUN cd /root/src/ruffle && cargo build --release --package=ruffle_desktop
  RUN cp /root/src/ruffle/target/release/ruffle_desktop /usr/local/bin/ruffle


# Add local user
ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID taser && \
    useradd -m -u $UID -g $GID taser
USER taser
WORKDIR /home/taser

# n-related commands
  RUN echo "libTAS /usr/local/bin/ruffle -g gl --no-gui /home/taser/tas/n_v14.swf &" > /home/taser/.bash_history
  COPY --chown=taser:taser external/n_v14.swf /home/taser/tas/
  COPY --chown=taser:taser docker_sound/ruffle.ini /home/taser/.config/libTAS/
  COPY --chown=taser:taser docker_sound/libTAS.ini /home/taser/.config/libTAS/

# run
  CMD bash
