FROM libtas_n

# recording tool + git for github action
  RUN apt-get update && apt-get install -y python3-setuptools python3-dev gcc

RUN groupadd -g 1000 user && \
    useradd -m -u 1000 -g 1000 -s /bin/bash user

# n-related commands
  RUN echo "export LEVEL='00-0' ; python3 optimize_replay.py auto ../n_levels/\${LEVEL}_rta.ltm --config 'examples/config.toml' --output ../n_levels/\${LEVEL}_optimised.ltm --replay-output wip/\${LEVEL}.txt --simulate-enemies --auto-stagnation-runs 3 --workers 15" >> /home/user/.bash_history && \
      chown 1000:1000 /home/user/.bash_history

# run
  WORKDIR /srv/optimiser
  USER 1000
  CMD bash
