FROM libtas_n

# recording tool + git for github action
  RUN apt-get update && apt-get install -y ffmpeg git

# n-related commands
  # ENV OUTFILE="ep"
  RUN echo "LEVEL='00-0' ; libTAS -i -r /home/n_levels/\$LEVEL.ltm --lua /home/lua/n_start.lua /usr/local/bin/ruffle_desktop -g gl --no-gui --width 792 /home/n_v14.swf &\nLEVEL='00-0'; libTAS -n -r /home/n_levels/\${LEVEL}_rta.ltm --lua /home/lua/n_ghost.lua -d /home/n_demos/\${LEVEL}.mp4 /usr/local/bin/ruffle_desktop -g gl --no-gui --width 792 /home/n_v14.swf\nOUTFILE='ep' ; libTAS -n -r /home/n_speedrun.ltm --lua /home/lua/n_ghost.lua -d /home/n_demos/\${OUTFILE}.mp4 /usr/local/bin/ruffle_desktop -g gl --no-gui --width 792 /home/n_v14.swf" > /root/.bash_history
  COPY docker/ruffle_desktop_recording.ini /root/.config/libTAS/ruffle_desktop.ini
  COPY docker/libTAS.ini /root/.config/libTAS/

# run
  WORKDIR /home
  CMD bash
