[local]
search = "population"
target_frame = 697
range = "597:697"
simulate-enemies = true
objective = "earliest-interaction"
target-object = "exit:0"
# secondary_objective = "max-x"
# require-interaction = ["testdoor:0"]
