[local]
search = "population"
target_frame = 378
range = "278:378"
simulate-enemies = true
objective = "earliest-interaction"
target-object = "exit:0"
# secondary_objective = "max-x"
# require-interaction = ["testdoor:0"]
