[local]
search = "population"
target_frame = 732
range = "632:732"
simulate-enemies = false
objective = "earliest-interaction"
target-object = "exit:0"
# secondary_objective = "max-x"
# require-interaction = ["testdoor:0"]
