[local]
search = "population"
target_frame = 608
range = "508:608"
simulate-enemies = false
objective = "earliest-interaction"
target-object = "exit:0"
# secondary_objective = "max-x"
# require-interaction = ["testdoor:0"]
