[local]
search = "population"
target_frame = 613
range = "513:613"
simulate-enemies = true
objective = "earliest-interaction"
target-object = "exit:0"
# secondary_objective = "max-x"
# require-interaction = ["testdoor:0"]
