GUI_LOADINGAPP = 0;
GUI_CONFIRMQUIT = 1;
GUI_LOADINGLEVEL = 2;
GUI_PRELEVEL = 3;
GUI_PAUSE = 4;
GUI_RETRYLEVEL = 5;
GUI_POSTLEVEL = 6;
GUI_DEBUGMENU = 7;
GUI_RESETTINGLEVEL = 8;
GUI_TEMP_EDITOR = 9;
GUI_TILE_EDITOR = 10;
GUI_OBJ_EDITOR = 11;
GUI_INGAMEDEMO = 12;
GUI_PASSEDEPISODE = 13;
GUI_RETRYLEVEL_SUICIDE = 14;
GUI_BEATGAME = 15;
GUI_GAMEOVER = 16;
GUI_KEYCONFIG = 17;
GUI_POSTLEVDEMO = 18;
GUI_POSTLEVELTIMETRIAL = 19;
GUI_PRELEVELTIMETRIAL = 20;
GUI_PAUSETIMETRIAL = 21;
GUI_PRELEVELPRACTISE = 22;
GUI_PRELEVELCUSTOM = 23;
GUI_POSTLEVELCUSTOM = 24;
GUI_LAST_STRING_INDEX = 24;
GUI_GOODBYE4 = 25;
GUI_VICTORY1 = 26;
GUI_PLAYMENU = 27;
GUI_CONFIGURE = 28;
GUI_DEFEAT = 29;
GUI_MAINMENU = 30;
GUI_HIGHSCOREMENU = 31;
GUI_CONTINUE = 32;
GUI_HELP = 33;
GUI_TIMETRIALMENU = 34;
GUI_GOODBYE5 = 35;
GUI_GOODBYE6 = 36;
GUI_GOODBYE7 = 37;
GUI_VICTORY2 = 38;
GUI_VICTORY3 = 39;
GUI_VICTORY4 = 40;
GUI_VICTORY5 = 41;
GUI_VICTORY6 = 42;
GUI_VICTORY7 = 43;
GUI_STORY = 44;
GUI_GOODBYE1 = 45;
GUI_CUSTOMMENU = 46;
GUI_GOODBYE2 = 47;
GUI_GOODBYE3 = 48;
NinjaGUI.prototype.InitData = function()
{
   this.guiList = new Object();
   this.guiList[GUI_LOADINGAPP] = "loading app..";
   this.guiList[GUI_CONFIRMQUIT] = "really quit? (y/n)";
   this.guiList[GUI_LOADINGLEVEL] = "loading level... (please wait)";
   this.guiList[GUI_PRELEVEL] = "level loaded..   press [spacebar] to begin,    [Q] to quit";
   this.guiList[GUI_PAUSE] = "game paused.. [spacebar] or [pause key]: unpause    [Q]: quit";
   this.guiList[GUI_RETRYLEVEL] = "ouch... press [spacebar] to try again, [R] to watch replay";
   this.guiList[GUI_POSTLEVEL] = "level complete! [spacebar] to continue, [R] to watch replay";
   this.guiList[GUI_RESETTINGLEVEL] = "resetting level... (please wait)";
   this.guiList[GUI_INGAMEDEMO] = "instant replay... press [spacebar] to try again.";
   this.guiList[GUI_RETRYLEVEL_SUICIDE] = "harsh, guy! press [spacebar] to try again.";
   this.guiList[GUI_BEATGAME] = "you have achieved transcendence!!!  ..[spacebar] for main menu";
   this.guiList[GUI_GAMEOVER] = "..you ran out of time. GAME OVER. press [spacebar] for main menu";
   this.guiList[GUI_PASSEDEPISODE] = "";
   this.guiList[GUI_KEYCONFIG] = "press your desired key; [Q] to abort";
   this.guiList[GUI_POSTLEVDEMO] = "instant replay... press [spacebar] to continue.";
   this.guiList[GUI_POSTLEVELTIMETRIAL] = "level complete! press [spacebar] to retry, [Q] to select new level";
   this.guiList[GUI_PRELEVELTIMETRIAL] = "level loaded; press [spacebar] to begin, [Q] to select new level";
   this.guiList[GUI_PAUSETIMETRIAL] = "game paused.. [spacebar] or [pause key]: unpause   [Q] to select new level";
   this.guiList[GUI_PRELEVELPRACTISE] = "level loaded..   [spacebar]: begin,   [Q]: quit,   [enter]: skip level";
   this.guiList[GUI_PRELEVELCUSTOM] = "level loaded..  press [spacebar] to begin, [Q] to select new level";
   this.guiList[GUI_POSTLEVELCUSTOM] = "level complete!  [spacebar]: retry, [Q]: return to user levels menu";
   this.guiList[GUI_HELP] = "help_menu";
   this.guiList[GUI_STORY] = "story_menu";
   this.guiList[GUI_MAINMENU] = "main_menu";
   this.guiList[GUI_CONTINUE] = "continue_menu";
   this.guiList[GUI_GOODBYE1] = "credits1";
   this.guiList[GUI_GOODBYE2] = "credits2";
   this.guiList[GUI_GOODBYE3] = "credits3";
   this.guiList[GUI_GOODBYE4] = "credits4";
   this.guiList[GUI_GOODBYE5] = "credits5";
   this.guiList[GUI_GOODBYE6] = "credits6";
   this.guiList[GUI_GOODBYE7] = "credits7";
   this.guiList[GUI_VICTORY1] = "beatgame1";
   this.guiList[GUI_VICTORY2] = "beatgame2";
   this.guiList[GUI_VICTORY3] = "beatgame3";
   this.guiList[GUI_VICTORY4] = "beatgame4";
   this.guiList[GUI_VICTORY5] = "beatgame5";
   this.guiList[GUI_VICTORY6] = "beatgame6";
   this.guiList[GUI_VICTORY7] = "beatgame7";
   this.guiList[GUI_DEFEAT] = "gameover";
   this.guiList[GUI_PLAYMENU] = "play_menu";
   this.guiList[GUI_CONFIGURE] = "config_menu";
   this.guiList[GUI_HIGHSCOREMENU] = "highscore_menu";
   this.guiList[GUI_TIMETRIALMENU] = "timetrial_menu";
   this.guiList[GUI_CUSTOMMENU] = "custom_menu";
   var _loc4_ = new Array();
   _loc4_.push("");
   _loc4_.push("**** EDIT MODE ****");
   _loc4_.push("[M]: return to main menu");
   _loc4_.push("[L]: load level (from textbox)");
   _loc4_.push("[S]: save level (to clipboard)");
   _loc4_.push("[J]: load empty map");
   _loc4_.push("[H]: load full map");
   _loc4_.push("[E]: edit level");
   _loc4_.push("[R]: reset objects");
   _loc4_.push("[T]: reset+edit");
   _loc4_.push("[P]: continue playing level");
   _loc4_.push("---");
   _loc4_.push("[1]: begin recording demo");
   _loc4_.push("[2]: stop recording demo");
   _loc4_.push("[Q]: begin demo playback (WARNING: resets objects)");
   _loc4_.push("[W]: end demo playback");
   _loc4_.push("[3]: load demo (from textbox)");
   _loc4_.push("[4]: save demo (to clipboard)");
   this.guiList[GUI_DEBUGMENU] = _loc4_;
   false;
   var _loc2_ = new Array();
   _loc2_.push("");
   _loc2_.push("");
   _loc2_.push("");
   _loc2_.push("");
   _loc2_.push("");
   _loc2_.push("");
   _loc2_.push("");
   _loc2_.push("");
   _loc2_.push("");
   _loc2_.push("");
   _loc2_.push("");
   _loc2_.push("");
   _loc2_.push("+++++++++++++< Ned >+++++++++++++++++++++++++++++++");
   _loc2_.push("   [insert] or [numpad 0]:  obj editor");
   _loc2_.push("   [delete] or [numpad .]:  tile editor");
   _loc2_.push("                   [PGDN]:  save data (to txtbox)");
   _loc2_.push("                   [PGUP]:  load data (from txtbox)");
   _loc2_.push("---------------------------------------------------");
   _loc2_.push("        [~] or [|] or [\\]:  back to debug menu");
   this.guiList[GUI_TEMP_EDITOR] = _loc2_;
   false;
   var _loc5_ = new Array();
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("");
   _loc5_.push("---(editing tiles)----------------");
   _loc5_.push("[insert] or [numpad 0]: obj editor");
   _loc5_.push("                [home]: edit menu");
   this.guiList[GUI_TILE_EDITOR] = _loc5_;
   false;
   var _loc3_ = new Array();
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("");
   _loc3_.push("--(editing objects)------------------");
   _loc3_.push("   [backspace + click]: delete object");
   _loc3_.push("[delete] or [numpad .]: tile editor");
   _loc3_.push("                [home]: edit menu");
   this.guiList[GUI_OBJ_EDITOR] = _loc3_;
   false;
};
