[local]
search = "population"
target_frame = 249
range = "149:249"
simulate-enemies = false
objective = "earliest-interaction"
target-object = "exit:0"
# secondary_objective = "max-x"
# require-interaction = ["testdoor:0"]
