[local]
search = "population"
target_frame = 522
range = "422:522"
simulate-enemies = true
objective = "earliest-interaction"
target-object = "exit:0"
# secondary_objective = "max-x"
# require-interaction = ["testdoor:0"]
